#!/bin/bash

# Credit to haskelling for this file. From https://github.com/haskelling/aoc2020/blob/main/get

if [ -r .cookie ]; then
  source .cookie
fi

thisyear="$(date +%Y)"
thismonth="$(TZ=EST date +%m)"
thisday="$(TZ=EST date +%d)"

year=2022
for day in {1..25}; do
  if [ "$thisyear" -ne "$year" -o "$thismonth" -ne 12 -o "$day" -gt "$thisday" ]; then
    exit 0
  fi
  filename="input/day$(printf '%02d' $day)".txt
  if [ -r "$filename" ]; then
    continue  # make sure we don't fetch the same file twice!
  fi
  echo "Fetching $filename"
  curl -A "ritobanrc@gmail.com via curl"  -sS -o "$filename" -b "$AOC_COOKIE" https://adventofcode.com/"$year"/day/"$day"/input
done
